displayName=Doom for ADHD
author=astolfogamer
description=Plugin focused on accessibility and quality of life for players with ADHD
tags=adha, doom, pvm
version=0.5
plugins=com.example.ExamplePlugin
build=standard